In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("../data/walmart_products.csv")

In [21]:
df.head()

,Uniq Id,Crawl Timestamp,Product Url,Product Name,Description,List Price,Sale Price,Brand,Item Number,Gtin,Package Size,Category,Postal Code,Available
0,019b67ef7f01103d8fb0a53e4c36daa7,2019-12-18 10:20:52 +0000,https://www.walmart.com/ip/La-Costena-Chipotle...,"La Costena Chipotle Peppers, 7 OZ (Pack of 12)",We aim to show you accurate product informati...,31.93,31.93,La Costeï¿½ï¿½a,NaN,139941530,NaN,"Food | Meal Solutions, Grains & Pasta | Canned...",NaN,True
1,3a4ff306dcc8a6e2bf720964d29b84c3,2019-12-18 17:21:48 +0000,https://www.walmart.com/ip/Equate-Triamcinolon...,Equate Triamcinolone Acetonide Nasal Allergy S...,We aim to show you accurate product informati...,10.48,10.48,Equate,569045548.0,632775553,NaN,Health | Equate | Equate Allergy | Equate Sinu...,NaN,True
2,80090549d7d176327b186353c7b28ca4,2019-12-18 17:46:41 +0000,https://www.walmart.com/ip/AduroSmart-ERIA-Sof...,AduroSmart ERIA Soft White Smart A19 Light Bul...,We aim to show you accurate product informati...,10.99,10.99,AduroSmart ERIA,568068849.0,281487005,NaN,Electronics | Smart Home | Smart Energy and Li...,NaN,True
3,151ee1c61a29bacfedb01cd500494b2f,2019-12-18 22:14:22 +0000,https://www.walmart.com/ip/24-Classic-Adjustab...,"24"" Classic Adjustable Balloon Fender Set Chro...",We aim to show you accurate product informati...,38.59,38.59,lowrider,NaN,133714060,NaN,Sports & Outdoors | Bikes | Bike Accessories |...,NaN,True
4,7b2ef8d41f65df121f6b4b9828cf8dad,2019-12-18 06:56:02 +0000,https://www.walmart.com/ip/Elephant-Shape-Sili...,Elephant Shape Silicone Drinkware Portable Sil...,We aim to show you accurate product informati...,5.81,5.81,Anself,NaN,104042139,NaN,Baby | Feeding | Sippy Cups: Alternatives to P...,NaN,True

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Uniq Id          30000 non-null  str
 1   Crawl Timestamp  30000 non-null  str
 2   Product Url      30000 non-null  str
 3   Product Name     30000 non-null  str
 4   Description      29947 non-null  str
 5   List Price       30000 non-null  float64
 6   Sale Price       30000 non-null  float64
 7   Brand            29436 non-null  str
 8   Item Number      8875 non-null   float64
 9   Gtin             30000 non-null  int64
 10  Package Size     0 non-null      float64
 11  Category         29983 non-null  str
 12  Postal Code      0 non-null      float64
 13  Available        30000 non-null  bool
dtypes: bool(1), float64(5), int64(1), str(7)
memory usage: 3.0 MB

In [23]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Product Url', 'Product Name',
       'Description', 'List Price', 'Sale Price', 'Brand', 'Item Number',
       'Gtin', 'Package Size', 'Category', 'Postal Code', 'Available'],
      dtype='str')

In [24]:
df.isnull().sum()

Uniq Id                0
Crawl Timestamp        0
Product Url            0
Product Name           0
Description           53
List Price             0
Sale Price             0
Brand                564
Item Number        21125
Gtin                   0
Package Size       30000
Category              17
Postal Code        30000
Available              0
dtype: int64

In [25]:
df = df[[
    "Product Name",
    "Brand",
    "Category",
    "List Price",
    "Sale Price",
    "Available"
]]

In [26]:
df

,Product Name,Brand,Category,List Price,Sale Price,Available
0,"La Costena Chipotle Peppers, 7 OZ (Pack of 12)",La Costeï¿½ï¿½a,"Food | Meal Solutions, Grains & Pasta | Canned...",31.93,31.93,True
1,Equate Triamcinolone Acetonide Nasal Allergy S...,Equate,Health | Equate | Equate Allergy | Equate Sinu...,10.48,10.48,True
2,AduroSmart ERIA Soft White Smart A19 Light Bul...,AduroSmart ERIA,Electronics | Smart Home | Smart Energy and Li...,10.99,10.99,True
3,"24"" Classic Adjustable Balloon Fender Set Chro...",lowrider,Sports & Outdoors | Bikes | Bike Accessories |...,38.59,38.59,True
4,Elephant Shape Silicone Drinkware Portable Sil...,Anself,Baby | Feeding | Sippy Cups: Alternatives to P...,5.81,5.81,True
...,...,...,...,...,...,...
29995,McCain Smiles,McCain,Food | Frozen Foods | Frozen Vegetables,0.00,0.00,False
29996,Shock Sox Fork Seal Guards 29-36mm Fork Tube 4...,Shock Sox,Sports & Outdoors | Bikes | Bike Components | ...,33.25,33.25,True
29997,Princes Gooseberries 300g,Princes,"Food | Meal Solutions, Grains & Pasta | Canned...",8.88,8.88,True
29998,Create Ion Grace 3/4 Inches Straight Hair Iron...,Create Ion,Beauty | Hair Care | Hair Styling Tools | Flat...,50.00,24.50,True
29999,Green Bell Takuminowaza Two Way Ear Pick Brass...,Takuminowaza,Beauty | Here for Every Beauty | Featured Shop...,6.00,4.20,True

In [27]:
df.columns = [
    "product_name",
    "brand",
    "category",
    "list_price",
    "sale_price",
    "available"
]

In [28]:
df.isnull().sum()

product_name      0
brand           564
category         17
list_price        0
sale_price        0
available         0
dtype: int64

In [29]:
df["brand"] = df["brand"].fillna("Unknown")

df = df.dropna(subset=["category"])

In [30]:
df

,product_name,brand,category,list_price,sale_price,available
0,"La Costena Chipotle Peppers, 7 OZ (Pack of 12)",La Costeï¿½ï¿½a,"Food | Meal Solutions, Grains & Pasta | Canned...",31.93,31.93,True
1,Equate Triamcinolone Acetonide Nasal Allergy S...,Equate,Health | Equate | Equate Allergy | Equate Sinu...,10.48,10.48,True
2,AduroSmart ERIA Soft White Smart A19 Light Bul...,AduroSmart ERIA,Electronics | Smart Home | Smart Energy and Li...,10.99,10.99,True
3,"24"" Classic Adjustable Balloon Fender Set Chro...",lowrider,Sports & Outdoors | Bikes | Bike Accessories |...,38.59,38.59,True
4,Elephant Shape Silicone Drinkware Portable Sil...,Anself,Baby | Feeding | Sippy Cups: Alternatives to P...,5.81,5.81,True
...,...,...,...,...,...,...
29995,McCain Smiles,McCain,Food | Frozen Foods | Frozen Vegetables,0.00,0.00,False
29996,Shock Sox Fork Seal Guards 29-36mm Fork Tube 4...,Shock Sox,Sports & Outdoors | Bikes | Bike Components | ...,33.25,33.25,True
29997,Princes Gooseberries 300g,Princes,"Food | Meal Solutions, Grains & Pasta | Canned...",8.88,8.88,True
29998,Create Ion Grace 3/4 Inches Straight Hair Iron...,Create Ion,Beauty | Hair Care | Hair Styling Tools | Flat...,50.00,24.50,True
29999,Green Bell Takuminowaza Two Way Ear Pick Brass...,Takuminowaza,Beauty | Here for Every Beauty | Featured Shop...,6.00,4.20,True

In [31]:
df = df.drop_duplicates()

In [32]:
df.shape

(29883, 6)

In [33]:
df["list_price"] = pd.to_numeric(df["list_price"])

df["sale_price"] = pd.to_numeric(df["sale_price"])

In [34]:
df[["list_price", "sale_price"]].describe()

         list_price    sale_price
count  29883.000000  29883.000000
mean      71.835624     70.968682
std      318.288074    317.962301
min        0.000000      0.000000
25%       10.920000     10.625000
50%       20.990000     20.500000
75%       45.215000     44.950000
max    13280.810000  13280.810000

In [35]:
df = df[
    (df["list_price"] > 0) &
    (df["sale_price"] > 0)
]

In [36]:
df[["list_price", "sale_price"]].describe()

         list_price    sale_price
count  29490.000000  29490.000000
mean      72.792945     71.914449
std      320.293197    319.967761
min        0.100000      0.100000
25%       11.090000     10.990000
50%       21.415000     20.990000
75%       45.990000     45.000000
max    13280.810000  13280.810000

In [37]:
df["discount_pct"] = (
    (df["list_price"] - df["sale_price"])
    / df["list_price"]
) * 100

df["discount_pct"] = df["discount_pct"].round(2)

In [38]:
df[["list_price", "sale_price", "discount_pct"]].head()

   list_price  sale_price  discount_pct
0       31.93       31.93           0.0
1       10.48       10.48           0.0
2       10.99       10.99           0.0
3       38.59       38.59           0.0
4        5.81        5.81           0.0

In [39]:
df.insert(0, "product_id", range(1, len(df) + 1))

In [40]:
df["main_category"] = df["category"].str.split("|").str[0].str.strip()

df["subcategory"] = df["category"].str.split("|").str[1].str.strip()

In [41]:
df[["category", "main_category", "subcategory"]].head()

,category,main_category,subcategory
0,"Food | Meal Solutions, Grains & Pasta | Canned...",Food,"Meal Solutions, Grains & Pasta"
1,Health | Equate | Equate Allergy | Equate Sinu...,Health,Equate
2,Electronics | Smart Home | Smart Energy and Li...,Electronics,Smart Home
3,Sports & Outdoors | Bikes | Bike Accessories |...,Sports & Outdoors,Bikes
4,Baby | Feeding | Sippy Cups: Alternatives to P...,Baby,Feeding

In [42]:
df = df[[
    "product_id",
    "product_name",
    "brand",
    "main_category",
    "subcategory",
    "list_price",
    "sale_price",
    "discount_pct",
    "available"
]]

In [43]:
df

,product_id,product_name,brand,main_category,subcategory,list_price,sale_price,discount_pct,available
0,1,"La Costena Chipotle Peppers, 7 OZ (Pack of 12)",La Costeï¿½ï¿½a,Food,"Meal Solutions, Grains & Pasta",31.93,31.93,0.0,True
1,2,Equate Triamcinolone Acetonide Nasal Allergy S...,Equate,Health,Equate,10.48,10.48,0.0,True
2,3,AduroSmart ERIA Soft White Smart A19 Light Bul...,AduroSmart ERIA,Electronics,Smart Home,10.99,10.99,0.0,True
3,4,"24"" Classic Adjustable Balloon Fender Set Chro...",lowrider,Sports & Outdoors,Bikes,38.59,38.59,0.0,True
4,5,Elephant Shape Silicone Drinkware Portable Sil...,Anself,Baby,Feeding,5.81,5.81,0.0,True
...,...,...,...,...,...,...,...,...,...
29994,29486,Sheng Xiang Zhen (ShengXiangZhen) Snack + OneN...,NineChef,Food,"Snacks, Cookies & Chips",45.99,45.99,0.0,True
29996,29487,Shock Sox Fork Seal Guards 29-36mm Fork Tube 4...,Shock Sox,Sports & Outdoors,Bikes,33.25,33.25,0.0,True
29997,29488,Princes Gooseberries 300g,Princes,Food,"Meal Solutions, Grains & Pasta",8.88,8.88,0.0,True
29998,29489,Create Ion Grace 3/4 Inches Straight Hair Iron...,Create Ion,Beauty,Hair Care,50.00,24.50,51.0,True
29999,29490,Green Bell Takuminowaza Two Way Ear Pick Brass...,Takuminowaza,Beauty,Here for Every Beauty,6.00,4.20,30.0,True

In [46]:
df.to_csv(
    "../data/products.csv",
    index=False
)